# Generated by Django 3.2.8 on 2021-10-26 22:31

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mushroom_name', models.CharField(max_length=255)),
                ('mushroom_image', models.ImageField(upload_to=mainapp.models.upload_image_path)),
                ('mushroom_description', models.TextField()),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.counties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MushroomCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(max_length=255)),
                ('mushroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mushroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
