# Generated by Django 3.2.8 on 2021-11-29 01:59

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=mainapp.models.upload_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
