# Generated by Django 3.2.8 on 2021-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_mushroomprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushrooPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mushroom_date_price', models.DateField()),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MushroomPrediction',
        ),
    ]
