# Generated by Django 3.2.8 on 2021-12-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20211201_0158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MushrooPrediction',
            new_name='MushroomPrediction',
        ),
    ]
