# Generated by Django 3.2.8 on 2021-11-27 13:24

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerassets',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='borrowerassets',
            name='asset_value',
        ),
        migrations.RemoveField(
            model_name='borrowerassets',
            name='ownership_percentage',
        ),
        migrations.RemoveField(
            model_name='borrowerassets',
            name='possession_since',
        ),
        migrations.AddField(
            model_name='borrowerassets',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='borrowerassets',
            name='mpesa_statement',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
