# Generated by Django 3.2.8 on 2021-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20211127_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproposal',
            name='loan_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
