# Generated by Django 3.2.8 on 2021-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loanproposal_loan_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproposal',
            name='cancel_date',
        ),
        migrations.AddField(
            model_name='loanproposal',
            name='loan_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
