# Generated by Django 3.2.8 on 2021-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20211129_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorfullfilmentproposal',
            name='disburd_date_to_borrower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investorfullfilmentproposal',
            name='release_date_from_investor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
